### ISSUE TITLE
How to access nested Superforms stores on `config`?

### ISSUE THREAD

**Issue by pheuter** [huntabyte/formsnap#26]
I'm trying to disable the form button based on the Superforms `$delayed` stored exposed on config:

```svelte
<Form.Button disabled={config.form.delayed}>
```

The issue is that it's nested under config.form and Svelte doesn't allow subscribing to stores that are nested in an object. How can I accomplish this functionality?

**Comment by huntabyte** [comment]
Hey @pheuter, you you should be able to access the delayed value via the `<Form.Root />` slot props, which will react since the store is passed as the value in the `<Form.Root />`. Working on updating the docs to reflect all the props but basically I'm passing all the things that you'd pull from `const { ... } = superForm()` as slot props.

```svelte
<Form.Root let:delayed let:message>
	{#if message}
		<p>{message}</p>
	{/if}
	<Form.Button disabled={delayed}>Submit</Form.Button>
</Form.Root>
```

Under the hood in the `<Form.Root/>` component this is basically what's happening:
```svelte
<script lang="ts">
	const { delayed, message, ... } = superForm(data.form, {...options}) 
</script>

<slot delayed={$delayed} message={$message} ... />
```

So it will update as the value of the store changes so your UI should react accordingly, even though it's not a store!

Let me know if you run into any issues with this and I'm happy to look into it!

**Comment by pheuter** [comment]
This should work, thanks!

**Comment by huntabyte** [comment]
Awesome, feel free to reopen the issue if problems arise!
